# Generated by Django 5.2.6 on 2025-09-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='links',
            field=models.CharField(max_length=200),
        ),
    ]
